"""Make review Image url nullable

Revision ID: 4a2bf1a87623
Revises: 3a557946011e
Create Date: 2025-04-25 10:07:59.763736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2bf1a87623'
down_revision = '3a557946011e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('img_url',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('img_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('review',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
